name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: cargo build --verbose
    - name: Run test
      run: cargo test --verbose
    - name: Run fmt
      run: cargo fmt -- --check
